name: Connect!
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  connect:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - run: echo step1
      - run: echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN" | rev
      - run: echo "$ACTIONS_ID_TOKEN_REQUEST_URL" | rev
      - uses: chkimes/actions-ssh@v0.1
      - run: echo step3
